apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: msoft-lab
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      nodePort: 32000
