apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: msoft-lab
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4= #admin
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4xMjM= #admin123 
